version: '3'
services:
  baguera:
    image: golang:1.13
    volumes:
      - .:/app/auth
    working_dir: /app/auth
    env_file:
      - development.env
    command: go run . -v
    ports:
      - "8082:8082"
    restart: always
    expose:
      - "8082"

  cachedb:
    image: redis
    command: redis-server --requirepass Root!2020
    ports:
      - "6379:6379"
