version: '3'
services:

  auth:
    image: golang:1.13
    volumes:
      - .:/app/auth
    working_dir: /app/auth
    env_file:
      - development.env
    command: go run . -v
    ports:
      - "8082:8082"
    restart: always
    expose:
      - "8082"
    depends_on: 
      - bagueradb
      - cachedb

  cachedb:
    image: redis
    command: redis-server --requirepass Root!2020
    ports:
      - "6379:6379"

  bagueradb:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cng_baguera"
    ports:
      - 5434:5432
    volumes:
      - ./db/auth/psql_db/schema:/docker-entrypoint-initdb.d
  
networks:
  default:
    external:
      name: cng